#!/bin/bash

#author  :  Hampton Ford
#purpose :  Removes everything but MP4s and PNGs. Made to streamline Chris' autogenerated Go-Pro footage cleanup.

if [ $# -eq 0 ]; then
	printf "USAGE:\n"
	printf "Run with ./GoProDel_NonMP3s.sh [drop_and_drop GoPro folder].\n\n\n"
fi

if [ $# -ne 1 ]; then
	printf "ERROR:\n"
	printf "You forgot to drag and drop the folder.\n"
	exit 0
fi

directory=$1

# prompt to backup
read -p "Would you like to make a backup folder? " CHOICE;
CHOICE=${CHOICE^^}
if [[ "${CHOICE}" == "Y" || "${CHOICE}" == "YES" ]]; then
	cd ${directory}
	cd ..
	cp -fr ${directory} ${directory}.backup
fi

cd ${directory}
files=$(ls $1)

for file in ${files}; do
	# Parse out name w/out extension
	f1=$(echo ${file} | cut -d '.' -f 1 | awk '{$1=$1};1')
	f2=$(echo ${file} | cut -d '.' -f 2 | awk '{$1=$1};1')
	f1=${f1^^}
	f2=${f2^^}
	# Delete all not mp4s or png
	if [[ "${f2}" != "MP4"  && "${f2}" != "PNG" ]]; then
		rm -f "${directory}/${file}" 2>&1
	fi
done

printf "Task completed successfully.\n"
